### ISSUE TITLE
Ability to have LB DNS names as outputs

### ISSUE THREAD

**Issue by tyler-public** [pivotal-cf/terraforming-aws#101]
Hi guys,

Big fans of your work. The client I'm working with has a need to be able to automate pulling the loadbalancer DNS names after they're created in order to do things like automate BOSH deployments using the load balancers (Concourse and the ATCs, is one of their use cases). I can't imagine we're the first/only ones that could use this, and overall I think it would be a great value add to the repository.

Specifically could the following resource's DNS names be exposed as outputs:

https://github.com/pivotal-cf/terraforming-aws/blob/master/modules/control_plane/lb.tf#L56

https://github.com/pivotal-cf/terraforming-aws/blob/master/modules/pas/lbs.tf#L32

https://github.com/pivotal-cf/terraforming-aws/blob/master/modules/pas/lbs.tf#L108

https://github.com/pivotal-cf/terraforming-aws/blob/master/modules/pas/lbs.tf#L166

**Comment by yogendra** [comment]
I am guessing putting following in the `modules/pas/output.tf` should give you what you need

```
output "pas_web_lb_dns" {
  value = ${aws_lb.web.dns_name}"
}
output "pas_ssh_lb_dns" {
  value = ${aws_lb.ssh.dns_name}"
}
output "pas_tcp_lb_dns" {
  value = ${aws_lb.tcp.dns_name}"
}
```

**Not a hands-on TF guy**

**Comment by tyler-public** [comment]
Hi @yogendra , this was the first thing we tried if I remember correctly. It unfortunately didn't work. We ended up having to hack some of the modules to output what we needed.
