### ISSUE TITLE
Add PKS related permissions in the Policy template. 

### ISSUE THREAD

**Issue by yjayaraman-pivotal** [pivotal-cf/terraforming-aws#103]
The AWS Ops policy terraforming-aws/modules/ops_manager/templates/iam_policy.json is fine for PAS but for PKS you need  elasticloadbalancing:DeregisterInstancesFromLoadBalancer,              elasticloadbalancing:RegisterInstancesWithLoadBalancer also in the template.

**Comment by genevieve** [comment]
Added https://github.com/pivotal-cf/terraforming-aws/commit/52184a4757d296284d3edc100a16a6102dee0fb2
