### ISSUE TITLE
ops_manager_security_group 

### ISSUE THREAD

**Issue by TommyKTheDJ** [pivotal-cf/terraforming-aws#107]
The security group `ops_manager_security_group` is created with the following code:
```
resource "aws_security_group" "ops_manager_security_group" {
  name        = "ops_manager_security_group"
  description = "Ops Manager Security Group"
  vpc_id      = "${var.vpc_id}"

  ingress {
    cidr_blocks = ["${var.private ? var.vpc_cidr : "0.0.0.0/0"}"]
    protocol    = "tcp"
    from_port   = 22
    to_port     = 22
  }

  ingress {
    cidr_blocks = ["${var.private ? var.vpc_cidr : "0.0.0.0/0"}"]
    protocol    = "tcp"
    from_port   = 80
    to_port     = 80
  }

  ingress {
    cidr_blocks = ["${var.private ? var.vpc_cidr : "0.0.0.0/0"}"]
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
  }

  egress {
    cidr_blocks = ["${var.private ? var.vpc_cidr : "0.0.0.0/0"}"]
    protocol    = "-1"
    from_port   = 0
    to_port     = 0
  }

  tags = "${merge(var.tags, map("Name", "${var.env_name}-ops-manager-security-group"))}"
}
```

However when BOSH Director for AWS is configured and you then apply the changes, the installation fails unless you manually add access to the newly created bosh/0 instance (which is given the same security group).  i.e. by adding an ingress rule that allows communication between all instances within the security group.

Result with default security group settings:
```
Started deploying
 Creating VM for instance 'bosh/0' from stemcell 'ami-0d32d60be3f351c8d light'... Finished (00:00:37)
 Waiting for the agent on VM 'i-0bf1b1565b39e1e3c' to be ready... Failed (00:10:16)
Failed deploying (00:10:54)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)


Deploying:
 Creating instance 'bosh/0':
   Waiting until instance is ready:
     Post https://vcap:&lt;redacted&gt;@10.0.16.5:6868/agent: dial tcp 10.0.16.5:6868: i/o timeout
```

Result with the following ingress rule added to `ops_manager_security_group`:
All traffic | All | All | sg-XXXXXXXXXXXXXXX (ops_manager_security_group)
```
tarted deploying
 Deleting VM 'i-0bf1b1565b39e1e3c'... Finished (00:00:03)
 Creating VM for instance 'bosh/0' from stemcell 'ami-0d32d60be3f351c8d light'... Finished (00:00:22)
 Waiting for the agent on VM 'i-0f127560ddc71dd85' to be ready... Finished (00:02:33)
 Creating disk... Finished (00:00:09)
```

I have found adding this into `modules/ops_manager_security_group.tf` fixes it for me:
```
  ingress {
    self      = "true"
    protocol  = "-1"
    from_port = 0
    to_port   = 0
  }
```
I'm happy to submit a PR if required.

**Comment by Polar-Beard** [comment]
hey @TommyKTheDJ - we actually deploy PAS to this template every time we make changes and have not run into this problem. What were you deploying and was this latest?

**Comment by TommyKTheDJ** [comment]
@Polar-Beard I was deploying BOSH Director for AWS as per the instructions here: https://docs.pivotal.io/runtimes/pks/1-3/aws-requirements.html, which links to both:
- https://docs.pivotal.io/pcf/om/2-4/aws/prepare-env-terraform.html
- https://docs.pivotal.io/pcf/om/2-4/aws/config-terraform.html
I was using the latest Terraform files from Pivnet (pivotal-cf-terraforming-aws-7e09091), but I can see that the file in this repository is the same.

**Comment by ksummersill2** [comment]
@TommyKTheDJ I am running into the same issue. Where you able to resolve? Its almost as if the Ops Manager cannot communicate with the newly created Bosh

**Comment by TommyKTheDJ** [comment]
Only by modifying the module locally and then using that, as per my OP:
I have found adding this into modules/ops_manager/security_group.tf fixes it for me:
```
  ingress {
    self      = "true"
    protocol  = "-1"
    from_port = 0
    to_port   = 0
  }
```

**Comment by ksummersill2** [comment]
@TommyKTheDJ, ok I will give that a shot. Did you have to restart the Ops Manager or Rebuild the Ops Manager before trying to install the Bosh Director with the changes?

**Comment by TommyKTheDJ** [comment]
No, just needed to re-run Terraform and then apply the staged changes for the director again.

**Comment by drawsmcgraw** [comment]
I ran into this issue as well. I referenced the [manual deployment on AWS docs](https://docs.pivotal.io/pivotalcf/2-2/om/aws/prepare-env-manual.html#pcfaws-om-secgrp) to be sure I wasn't missing any ports. I added the additional ports and retried but the deploy still failed. In the end, I had the following ports opened up inside the security group:

```
25555
8443
6868
8844
```

`443`,`80`, and `22` were also open from outside the vpc.

The deploy still failed. I gave up and opened up every port inside the security group (what @TommyKTheDJ mentioned). That succeeded. 

I don't know what the list of ports should be and I don't know what "right" looks like to y'all but I'm going to file a PR to get the conversation started. I lost a fair amount of time to this bug and I'd like to prevent it from happening again.

**Comment by Polar-Beard** [comment]
@TommyKTheDJ @drawsmcgraw @ksummersill2 there is an acknowledged issue with the current documentation available for configuring PKS when using our repo, so I apologize for that inconvenience. 

However, to your issues, we currently deploy PKS on AWS in our pipelines, and we do not encounter the errors you've described here, which leads me to believe that there is something different that you're doing when configuring your director/PKS that is causing this issue. Could you share your configuration for the director/PKS so I can try to find the disconnect? Thanks! 😃

**Comment by drawsmcgraw** [comment]
Welp! I just gave it another try on a brand new ecosystem. I deleted the Bosh Director, ran a `terraform destroy`, and started the deployment all over again with the latest version of the Terraform files from Pivnet (`0639c54`, according to the directory name). The deployment went just fine. I'm going to chalk this up to either operator error or some transient issue that cannot reliably be reproduced. 

In light of this, I'm going to close my PR.

@TommyKTheDJ, have you done any more deployments and run into this issue?
@Polar-Beard, thanks for your help and patience!

For posterity (those in the future, reading this), the documentation issues that @Polar-Beard mentioned are related to the creation of vm_extensions. You need to create the vm_extensions, then update the product config to use it. 

For me, it was PAS, so see [this link](https://github.com/pivotal-cf/terraforming-aws/blob/d4482bb733e34a7e3c4a48ef55f65610a91a57eb/ci/tasks/custom-vm-extensions.sh#L10) (vm_extension) and [this link](https://github.com/pivotal-cf/terraforming-aws/blob/d4482bb733e34a7e3c4a48ef55f65610a91a57eb/ci/assets/template/srt-config.yml) for the updated PAS config for examples.

**Comment by drawsmcgraw** [comment]
@Polar-Beard I'm convinced my issue here was user-error or a sporadic, iaas-related error. For what it's worth to you, I'd be fine with closing this issue.

**Comment by Polar-Beard** [comment]
Thanks for running through it again @drawsmcgraw. Will close 👍
