### ISSUE TITLE
Created NS record has only 1 value (not 1 per name server)

### ISSUE THREAD

**Issue by noizwaves** [pivotal-cf/terraforming-aws#125]
### Summary

When terraforming a control plane with `env_name="cp"` and `dns_suffix="aws.63r53rk54v0r.com"` the name sever records are incorrectly being created as a single string, instead of a list of strings.

Happy to be wrong on this, so please let me know if I've got things wrong.

### Expected Behavior

<img width="1552" alt="expected AWS" src="https://user-images.githubusercontent.com/1007983/55653697-8c384480-57ac-11e9-8b06-63029cd6f78d.png">
<img width="585" alt="expected dig" src="https://user-images.githubusercontent.com/1007983/55653700-8e020800-57ac-11e9-9396-57adc9124516.png">

### Actual Behavior

<img width="1552" alt="actual AWS" src="https://user-images.githubusercontent.com/1007983/55653704-935f5280-57ac-11e9-819a-27e0386d8315.png">
<img width="1107" alt="actual dig" src="https://user-images.githubusercontent.com/1007983/55653708-965a4300-57ac-11e9-89ea-ed2d01237d91.png">

### Proposed fix

I've fixed the issue in a hard fork of `terraforming-aws` in [this commit](https://github.com/noizwaves/pcf-aws-63r53rk54v0r/commit/18c2356f0fe15f0442e99d8f3f458ced2e8adf23). I'm happy to make this a PR too.

**Comment by nthomson-pivotal** [comment]
Just got bit by this as well, LetsEncrypt is freaking out when it tries to use DNS challenge with the current configuration.

**Comment by nmahoney-pivotal** [comment]
This got fixed yesterday, but it is part of a larger commit that is still being worked on. @zachgersh could you link the commit here when you push it?

**Comment by nmahoney-pivotal** [comment]
I believe [this](https://github.com/pivotal-cf/terraforming-aws/commit/b497b2060b36ab01addc1afc1b611efa64ee769a) is the commit. I expect a release containing this fix to be published this week.

**Comment by genevieve** [comment]
Shipped in v0.52.0
