### ISSUE TITLE
NAT gateway EIP should be named

### ISSUE THREAD

**Issue by iplay88keys** [pivotal-cf/terraforming-aws#140]
When running `Terraform Apply` with the `terraforming-pas` files, the EIP for the created NAT Gateway is not labeled in the AWS console. This may be a problem with other created EIPs for NAT gateways through the `terraforming-*` files.

EIP View:
![image](https://user-images.githubusercontent.com/3587901/62578261-ea119180-b85d-11e9-97c0-37d65c85ecbb.png)

NAT Gateways View:
![image](https://user-images.githubusercontent.com/3587901/62578315-1200f500-b85e-11e9-875a-8b84c89553dd.png)

**Comment by genevieve** [comment]
Hey @iplay88keys. 

It doesn't appear that the eip type has a configuration option for name. https://www.terraform.io/docs/providers/aws/r/eip.html

You can use the tags parameter for easier identification of resources. https://github.com/pivotal-cf/terraforming-aws/blob/bbdf8ef4e8d04970481007bab826f9976d24e949/modules/infra/nat.tf#L43
