### ISSUE TITLE
Paving-pas github repo

### ISSUE THREAD

**Issue by quixoticmonk** [pivotal-cf/terraforming-aws#145]
**From the ReadMe** :The intention is to archive this repo. The new repos for the templates can be found here: paving-pas and paving-pks. 

The links for the paving-pas and paving-pks repos give a 404. Are they not publicly available ?

**Comment by genevieve** [comment]
Hi @quixoticmonk. We've removed the deprecation notice and links to those repos. Please continue to use this repo for the aws templates.
