### ISSUE TITLE
Terraform plan fails while trying to install Ops Manager on AWS

### ISSUE THREAD

**Issue by dilipk8** [pivotal-cf/terraforming-aws#148]
The goal is to install PKS on AWS. To do so i referred - https://docs.pivotal.io/pcf/om/2-5/aws/prepare-env-terraform.html to start with .
i added the terraform.tfvars file. Did a terraform init from terraform-pks directory that i got from the AWS template available on the Pivotal Network, which worked fine and then when i try  to run terraform plan i get this error:
Invalid value "terraform.tfvars" for flag -var-file-default:Error parsing terraform.tfvars: At 63:8 heredoc not terminated

I checked my terraform.tfvars file and it looked okay to me.
Terraform version - 0.10.8 on Windows

**Comment by genevieve** [comment]
Hi @dilipk8. The error message is probably indicating that cert or key values are incorrectly formatted in your `terraform.tfvars` file. In the below example, the "heredoc" starts with `<<SSL_CERT` and is terminated with `SSL_CERT`.

```
ssl_cert = <<SSL_CERT
-----BEGIN CERTIFICATE-----
YOUR-CERTIFICATE
-----END CERTIFICATE-----
SSL_CERT
```

**Comment by dilipk8** [comment]
Thanks @genevieve
