### ISSUE TITLE
Minimimum set of AWS IaaM policies

### ISSUE THREAD

**Issue by phopper-pivotal** [pivotal-cf/terraforming-aws#15]
Notice that a set of IaaM policies is defined here; https://github.com/pivotal-cf/terraforming-aws/blob/master/ops_manager/templates/iam_policy.json. To run the terraform script on AWS does one need to be an admin or of a privileged user to execute?

I've got a unique situation that policies are controlled by an organization and they require a policy that needs to be set specifically for the running of the terraform template. This would make an assumption that the policy would need to be referenced directly instead of setting the policy explicitly. Without forking the repository, is there a means to accommodate.

**Comment by kkallday** [comment]
Hi @phopper-pivotal,

We're currently investigating the minimal IAM policies needed to run these terraform templates ([tracker story](https://www.pivotaltracker.com/story/show/148044207)).

Thanks for bringing this to our attention.

- Kevin & @joshzarrabi
