### ISSUE TITLE
terraforming-aws vs pcf-pipelines

### ISSUE THREAD

**Issue by jgeorge300** [pivotal-cf/terraforming-aws#22]
Is there a difference between the terraforming code in the install-aws directory of the [pcf-pipelines ](https://github.com/pivotal-cf/pcf-pipelines) project and this project?

**Comment by evanfarrar** [comment]
@jgeorge300 there are some incidental differences between the two but no intentional differences. We are working with the pipelines team to see what it would take for them to use this repo.
