### ISSUE TITLE
Generated RDS passwords include invalid mysql URI's during PAS install

### ISSUE THREAD

**Issue by Pivotal-Jayson-Hairston** [pivotal-cf/terraforming-aws#28]
I had a foundation that terraform created an output of:
```
rds_password = i4fq]QpVzC7G&j4>
```

---

Later on in the PAS install bosh fails with error: 
```
Task 203 | 20:46:06 | Updating instance cloud_controller: cloud_controller/a2cca9d0-2349-4c2c-a836-964569491c84 (0) (canary) (00:04:08)
                    L Error: Action Failed get_task: Task c0640d40-f8f0-4f9f-6187-8964e0d85dd1 result: 1 of 6 pre-start scripts failed. Failed Jobs: cloud_controller_ng. Successful Jobs: routing-api, route_registrar, syslog_forwarder, bosh-dns, consul_agent.
```

---

Digging further into the cloud Controller VM and the log, **/var/vcap/sys/log/cloud_controller_ng/pre-start.stderr.log**, I get this error:

```
[2018-02-02 20:50:08+0000] URI::InvalidURIError: bad URI(is not URI?): mysql2://rds_admin:i4fq]QpVzC7G&j4%3E@terraformed.cs6ujk8p5jm9.us-east-1.rds.amazonaws.com:3306/ccdb
```
`>` in the password gets changed to URI Encoded value `%3E` which is still not the correct password for RDS.

**Comment by genevieve** [comment]
Hey @Pivotal-Jayson-Hairston!

Did you want to include the error output?

I believe this has been solved in the latest release by removing the special characters from the rds password!

**Comment by Pivotal-Jayson-Hairston** [comment]
yeah, sorry, somehow my paste submitted the issue before I was done. I have updated the comment with the details and errors.

**Comment by genevieve** [comment]
Great. This should be fixed in the latest release. Could you run the latest?

**Comment by Pivotal-Jayson-Hairston** [comment]
Oh Perfect! That was fast! Will do Thanks!
