### ISSUE TITLE
IAM User doesn't have enough permissions

### ISSUE THREAD

**Issue by nevenc-pivotal** [pivotal-cf/terraforming-aws#30]
Terraform scripts create a new IAM user with various permissions. It doesn't seem it is enough for kickstarting OpsManager and Bosh Director creation.

Here's the error message (when "Apply Changes" for the first time after configuring Director tile):
```
creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3468.21):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"You are not authorized to perform this operation.","ok_to_retry":false}
```
There are two policies created for the IAM user:
[DEPLOYMENT_ert] (https://github.com/pivotal-cf/terraforming-aws/files/1706600/ert.json.txt)
[DEPLOYMENT_ops_manager] (https://github.com/pivotal-cf/terraforming-aws/files/1706601/ops-manager.json.txt)

Error goes away when I use another IAM user with "AdministratorAccess" role.

**Comment by haydonryan** [comment]
@nevenc-pivotal would it be ec2:copyImage? We discovered that yesterday.

**Comment by nevenc-pivotal** [comment]
probably ;)

didn't have time to troubleshoot which permission was missing :))

just used allmighty AdministratorAccess role



Neven Cvetkovic | Senior Platform Architect
Mobile: +46 725 40 33 66 |  email: nevenc@pivotal.io

<http://www.pivotal.io/>

Follow Us: Twitter <http://www.twitter.com/pivotal> | LinkedIn
<http://www.linkedin.com/company/pivotalsoftware> | SlideShare
<http://www.slideshare.net/pivotal> | Facebook
<http://www.facebook.com/pivotalsoftware> | YouTube
<http://www.youtube.com/gopivotal>

**Comment by haydonryan** [comment]
We found that at a customer site, and tracing through the AWS CPI it looks like it’s hitting that. Can link you to the line if you’re interested.

**Comment by nevenc-pivotal** [comment]
Please do @haydonryan

**Comment by genevieve** [comment]
Hey @nevenc-pivotal. Could you give us more details on what steps you followed to see this error?

We have not seen this error in our pipelines, in release engineering's pipelines, and in other user's environments.

Have you somehow changed the default stemcell that the director is deployed with? This doesn't seem to be available through the api and likely the only way to change a stemcell is through an upgrade.

We can add the `ec2:CopyImage` rights to the policy, but would like a way to reproduce this issue to know if it has been solved.

**Comment by kreutziger** [comment]
I was running into the issue today as well with the release of the pcf pipelines of v0.23.1. We are using AWS on regions eu-west-1 and eu-central-1.

**Comment by arutsudar** [comment]
I got a similar error which says -
```
Deleting stemcell from cloud:
  CPI 'delete_stemcell' method responded with error: CmdError{"type":"Unknown","message":"You are not authorized to perform this operation.","ok_to_retry":false}
```

I added `ec2:DeregisterImage` action in the policy of AWS user, and it worked.

Hope this might be helpful for someone who comes across a similar of same error.
