### ISSUE TITLE
AWS Roles invalid

### ISSUE THREAD

**Issue by neil-hickey** [pivotal-cf/terraforming-aws#45]
The following recommended roles do not exist on AWS anymore:

- AmazonIAMFullAccess
- AmazonKMSFullAccess

---

Without some additional roles which I suppose were encompassed in these ones above, the terraform fails.

It would be great to update these to what they have been renamed / moved to on AWS today.

![screen shot 2018-04-12 at 17 31 40](https://user-images.githubusercontent.com/6075668/38690997-6e0931da-3e77-11e8-9b3d-1ad5dddb9b45.png)

all other roles as defined in the readme are still available:

![screen shot 2018-04-12 at 17 32 44](https://user-images.githubusercontent.com/6075668/38691048-92603600-3e77-11e8-8a95-b7714ae2de7b.png)

**Comment by genevieve** [comment]
Hey @neil-hickey were there roles for KMS access and IAM access?

**Comment by genevieve** [comment]
I think the correct ones are `IAMFullAccess` and `AWSKeyManagementServicePowerUser`
