### ISSUE TITLE
Add 'CopyImage' permission to IAM user created

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/terraforming-aws#47]
This is related to this [PR](https://github.com/pivotal-cf/pcf-pipelines/pull/292).

The short, when using the these terraforming scripts, and then following the docs to upgrade OpsMan another permission is required on the user.

-- @jtarchie && @fredwangwang

**Comment by genevieve** [comment]
Which IAM Policy do you think needs to be changed? This policy specifies CopyImage: https://github.com/pivotal-cf/terraforming-aws/blob/master/ops_manager/templates/iam_policy.json#L112

**Comment by jtarchie** [comment]
Closing, we should have done a better search.
