### ISSUE TITLE
PKS Support

### ISSUE THREAD

**Issue by kkallday** [pivotal-cf/terraforming-aws#64]
Hi,

The PKS Releng team has began testing the product on AWS. Here are some of the infrastructure prerequisites PKS:

- opsman
- VPC
- subnets in each availability zone
- security groups
- DNS record for opsman
- IAM Role with EC2, ELB, S3 permissions

As you can see most of the resources above are already created by the templates however, the IAM role is currently not part of the templates. PKS requires a subset of the resources that are currently being created by the templates. For instance, the product doesn't need S3 buckets, DNS records for TCP, Diego Brain SSH endpoints, or ELBs.

Instead of adding `count = ${var.pks ? 0 : 1}` to all the PAS related resources, I'm proposing that common infrastructure resources live at the top level, PAS related resources in a directory/module named `pas` and PKS related resources in `pks`.
```
terraforming-aws/
  iam.tf
  ...
  dns.tf
  pks/
    firewall.tf
    ...
    iam.tf
  pas/
    dns.tf (pas specific dns records)
    iam.tf
    ...
    elb.tf
    buckets.tf
```

Looking forward to hearing your feedback and if this aligns with any long-term plans you have for the templates. If this idea sounds good, I'd be open to making a PR for this change.

Thanks,

Kevin

**Comment by cdutra** [comment]
Hi @kkallday, thanks for the help yesterday! We have a commit that will be ready to be pushed today. We only need to update the README.md and everything should be good to go.

**Comment by kkallday** [comment]
Cool thanks @cdutra for following up! We are hoping to start using this in the coming weeks.
