### ISSUE TITLE
Problems with opsmgr being handled by terraform

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-aws#66]
[Opsmgr comes packaged as an AMI defined within terraform.](https://github.com/pivotal-cf/terraforming-aws/blob/master/ops_manager/variables.tf#L9)

But when it comes time to upgrade the version of opsmgr, things get tricky. You have to...

1. backup your opsmgr installation to something like s3
2. find out the opsmgr AMI corresponding to your IaaS
3. update/run the terraform to use that AMI
4. re-import your opsmgr installation

This is a stateful operation; terraform doesn't know anything about what's actually running on the EC2 instance. It'll gladly blow it away and replace it with a new EC2 instance without any regard for running processes, persistent volumes, etc. So I, as an operator, am responsible for maintaining/backing up/restoring the state of opsmgr. This sounds like something BOSH is designed to do.

[The `pcf-pipelines` project](https://github.com/pivotal-cf/pcf-pipelines/tree/master/upgrade-ops-manager/aws) dealt with upgrading opsmgr by doing some funky stuff with `cliaas` to replace the VM. But even that wouldn't work if your VPC was managed by terraform. If you update the opsmgr VM without terraform being aware of it, the next time terraform runs it will replace your _new_ opsmgr VM with the _old_ AMI.

I'm curious if there's a medium/long-term solution to this problem. Specifically: **does Pivotal have any plans to refactor opsmgr into a BOSH-managed resource rather than a terraform-managed resource?**

Thanks for your time, I appreciate it!

**Comment by aegershman** [comment]
Closing this as I imagine the problem won't be solved here / Pivotal is aware of it. I just wanted to point it out. Thanks!

**Comment by nmahoney-pivotal** [comment]
Sorry your issue slipped through the cracks. We are working on some solutions for upgrading Ops Manager. There are some open questions, but the Ops Manager VM won't be handled by Terraform. [We added a variable](https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pas/variables.tf#L57) to skip creation of the Ops Manager VM to support this.

**Comment by aegershman** [comment]
No worries at all. I just wanted to point it out. Thanks for your time.
