### ISSUE TITLE
release 21 prompting for var.private_route_table_ids

### ISSUE THREAD

**Issue by dkalemba** [pivotal-cf/terraforming-aws#70]
Using release 21 to generate the terraform plan presents a prompt to enter a value for var.private_route_table_ids

There is no mention of this in any of the documentation.  What is intended here?

**Comment by cdutra** [comment]
@dkalemba Are you terraforming pas or pks?
You need to perform one of the following steps before `terraform apply`:
```
cd terraforming-pas
```
or
```
cd terraforming-pks
```

**Comment by dkalemba** [comment]
PKS.  I see what happened now, i actually changed to the pks directory.  The README.md kinda fooled me...

```
cd into the proper directory:
pas
pks
```

**Comment by cdutra** [comment]
@dkalemba The documentation was misleading since those were links to the `terraforming-pas` and `terraforming-pks`. I just updated the README to be more clear about the path. Thanks for the feedback!

**Comment by dkalemba** [comment]
thanks for the help!  we can close this out!
