### ISSUE TITLE
Creation of separate PKS opsmgr / s3 buckets for that PKS opsmgr?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-aws#71]
I am under the impression it is best practice to have a separate opsmgr for PAS and PKS. I'd like to stand up a separate opsmgr for PKS, but have it be within the same foundation as PAS.

So two questions:
- Is there an intended way to configure the terraform to create both a PAS and PKS opsmgr within in the same environment? E.g., multiple opsmgrs but each for different purposes?
- How should the opsmgrs + opsmgr resources be differentiated? For example, [with the opsmgr's `s3` bucket, there appears to be a var for `bucket-suffix` var on the end. Is that intended to be used for differentiation? E.g., `sandbox-ops-manager-bucket-pks` and `sandbox-ops-manager-bucket-pas`?](https://github.com/pivotal-cf/terraforming-aws/blob/master/ops_manager/bucket.tf#L2) 

Thanks a ton. Any advice is appreciated!

**Comment by cdutra** [comment]
@aegershman the `terraforming-pas` will deploy a ops manager with all IaaS resources suitable to deploy PAS. The `terrafaform-pks`will deploy a separate unrelated ops manager with all IaaS resources suitable to deploy PKS. Totally separate environments from each other.

**Comment by aegershman** [comment]
[Gotcha, I see how that works now](https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pks/main.tf#L43-L62).

By the way, [the `p-automation` team](https://github.com/pivotal-cf/docs-book-platform-automation) appears to be working on a toolchain which allows an opsmgr to be deployed/upgraded independently from the terraform (it doesn't appear GA at the moment). It seems as though if their process is used, the only thing that would be required to be defined in terraform is the `ops-manager-s3` to store the opsmgr state. Everything else would be managed by the `p-automation` toolchain. Just figured I'd share 👍 

Thanks for your time

**Comment by cdutra** [comment]
@aegershman Of course! Feel free to always ask questions and also to ping us on Slack if you wish.
