### ISSUE TITLE
Consider switching to using NAT gateways rather than NAT instances

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-aws#77]
Inspired by [this issue in the `BBL` repo](https://github.com/cloudfoundry/bosh-bootloader/issues/297):

Instead of using NAT instances, which require maintaining the AMI && are not HA, why not use AWS NAT gateways? They're a managed service, do not incur any downtime, and do not require the same level of maintenance as NAT instances.

(EDIT: accidentally swapped "instance" and "gateway". Oops)

**Comment by voor** [comment]
This one will become very important, since the default limit for elastic IP addresses per region is 5, which means if we're creating an Elastic IP for 3 Ops Managers (PAS, Control Plane, PKS), and 3 NAT instances we're already over the limit of 5.

**Comment by voor** [comment]
Nevermind, looks like you need an EIP for the nat service as well.

I've been playing around with the following:
https://github.com/voor/terraforming-aws/commit/0e8e973e16a360d9bc090aecd8f41dfb99dd2bc0

And it seems to be working pretty well.

**Comment by cdutra** [comment]
@aegershman That's a good point. I don't see a reason why not use Nat Gateways.
@voor Would you like to PR the changes?

Thanks!

**Comment by voor** [comment]
Yes, they're in my branch and I've been playing around with it, will get a pr sometime next week

**Comment by cdutra** [comment]
@xyloman No anymore, since Network load balancers on AWS don't support that. We still create a certificate in the ACM, however we will remove it soon because they aren't being used.

**Comment by aegershman** [comment]
Perhaps this is a separate issue, but is there a reason ALBs weren't used instead? I'm under the impression ALBs can have multiple certs dynamically associated to them without having to chain them all into a single cert. That feature makes it a breeze to

**Comment by voor** [comment]
Alb and elb are layer 7 and has some performance implications.  Not sure why they switched but that might have been a motivation.

**Comment by cdutra** [comment]
@aegershman You can still set the certificate in Ops Manager. We still generate certificates and we output them. The only thing we don't create is add the Certificate in ACM.
Maybe another issue would be more suitable to discuss this. Thank you for the feedback!

**Comment by xyloman** [comment]
@cdutra ALBs provide an operational improvement in that Amazon Certificate Manager will issue and rotate SSL certificates that are associated to the ALB.  They are also free to use on AWS which if we are putting a signed certificate into ops manager that will have to come from a trusted authority which would have an additional cost associated to it.  The ALB leverages renegotation to only provide a certificate that matches a given domain name.  So for instance if both foo.example.com and bar.test.com are pointed at the same ALB only the certificate that matches foo.example.com will be returned.

**Comment by cdutra** [comment]
@xyloman I agree, both load balancers have their own benefits and drawbacks. I'd advice to file a different issue highlighting the benefits supporting both. This issue is unrelated to load balancers.
@evanfarrar might have comments about.

Thanks!

**Comment by voor** [comment]
Should have been merged into master now, this can probably be closed.
