### ISSUE TITLE
Pin AWS terraform provider or else changes will take place without you knowing it

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-aws#79]
[We don't specify a version for the aws terraform-provider.](https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pas/main.tf#L1-L5).

We pin the version of terraform used to `0.11.7`, but [as per the terraform doc](https://www.terraform.io/docs/configuration/providers.html#provider-versions), terraform _provider_ versions can change at an independent rate. If you don't pin the version of the _provider_ used, it can change without you knowing it.

When [terraform-provider-aws 1.42.0 was released yesterday](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1420-october-31-2018), our terraform broke and was unable provision acm certs correctly. When we pinned the version back to `1.41.0`, everything went back to working just fine.

We *just* got bit by this in our sandbox environment. Luckily we caught it there before we rolled out any more changes to production. I'd strongly advise adding something like `version = "<= 1.41.0"` to the terraform provider configuration

**Comment by joshzarrabi** [comment]
@aegershman We don't pin the terraform version in these templates, we just say that it has to be less than `.12` which has not been released yet: https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pas/main.tf#L7-L9. We want to encourage everyone to roll forward, and we test with the latest version of terraform in our pipelines.

I'm curious why you all pin the version of terraform to 11.7?

cc @Polar-Beard

**Comment by aegershman** [comment]
We pin the version of terraform to 11.7 simply by happenstance-- we're using Concourse to handle terraform changes, and the Concourse terraform resource we're using is pinned to 11.7.

I'm referring to the version of the AWS terraform provider, though. Not the version of terraform itself.

**Comment by joshzarrabi** [comment]
I think if you let your version of terraform be on latest then you should be fine.
