### ISSUE TITLE
Document permission level on AWS account used by Terraform

### ISSUE THREAD

**Issue by henderjm** [pivotal-cf/terraforming-aws#8]
We're trying to bootstrap OpsManager 1.9 on AWS using this repo. We ran into an issue wherein we don't know what set of IAM permissions are needed by the AWS user used by Terraform.

It will be nice if you could document the set of permissions needed. Otherwise the only workaround is to give the AWS user full access.

**Comment by joshzarrabi** [comment]
We have an open pull request #12 that will add the documentation covering this. We will merge it once we have resolved a few issues with it.

Thanks.
