### ISSUE TITLE
Consider using credentials file rather than incorporating it into main.tf

### ISSUE THREAD

**Issue by voor** [pivotal-cf/terraforming-aws#83]
Certain customers have mechanisms that will generate a credentials file for terraform for them, or else they're using `AWS_SESSION_TOKEN` which negate the ability to even use a `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.  Consider removing these files from `main.tf` for PAS and PKS.

**Comment by cdutra** [comment]
@voor What files? i don't see files in main.tf

**Comment by voor** [comment]
https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pas/main.tf#L1-L5
and
https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pks/main.tf#L1-L5

You can recreate this sometime by doing the following:

1. Delete these sections from the files.
1. Delete this section https://github.com/pivotal-cf/terraforming-aws/blob/master/terraforming-pks/variables.tf#L9-L11 (or equivalent in pas)
1. Populate `AWS_SECRET_ACCESS_KEY` environment variable
1. Populate `AWS_ACCESS_KEY_ID` environment variable
1. Populate `AWS_DEFAULT_REGION` environment variable
1. Run `terraform plan ...` and `terraform apply` as before with no problems.

You still need `region` populated since that variable is used elsewhere.

See: https://www.terraform.io/docs/providers/aws/ for more ways to do it.

**Comment by voor** [comment]
Specifically, a lot of customers are using https://www.vaultproject.io/docs/secrets/aws/index.html to issue time sensitive tokens that expire, this is already issued with vault so it integrates nicely if you leave credentials **out** of the terraform stuff.

**Comment by cdutra** [comment]
@voor Thank makes sense and avoids having credentials on disk. However this should already by possible as of now, [terraform supports setting variables through environments variables](https://www.terraform.io/docs/configuration/environment-variables.html#tf_var_name).

So as of now you can:
```
export TF_VAR_ access_key ="key"
export TF_VAR_ secret_key ="secret"
export TF_VAR_region="us-west-1"
```

Thanks!
