### ISSUE TITLE
Using PCF terraform with AWS organization accounts

### ISSUE THREAD

**Issue by zopechetan** [pivotal-cf/terraforming-aws#94]
We have to setup PCF on AWS organization account with federation enabled. There are some restrictions using this account like we cannot create new IAM users .  I have to deploy PCF using the shared account of federation, which does not have permissions to create a new IAM user.

Using terraform to deploy PCF , requires a new IAM user to be created. I have access to this shared account via role(which is assumed) .

I am getting this error:
aws_iam_user.ops_manager: Error creating IAM User bwce_om_user: AccessDenied: User: arn:aws:sts::XXXXXXXXXX:assumed-role/EC2Role/1547621556019946500 is not authorized to perform: iam:CreateUser on resource: arn:aws:iam::XXXXXXXXXXXX:user/bwce_om_user with an explicit deny

I need to know what needs to be changed in terraform ? So that there is no need to create new IAM user and I can use the role instead of  it .

**Comment by zopechetan** [comment]
Does PCF terraform templates supports AWS organization account, where user has restricted access such as not able to create IAM user ?

**Comment by nmahoney-pivotal** [comment]
Glad you figured it out :)
